version: "3"
services:
  apiserver:
    image: platform-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.4
    restart: always
    ports:
    - 27017:27017